In [3]:
%pip install lxml html5lib beautifulsoup4

Requirement already satisfied: lxml in c:\users\shrad\anaconda3\lib\site-packages (4.9.3)
Requirement already satisfied: html5lib in c:\users\shrad\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\shrad\anaconda3\lib\site-packages (4.12.2)
Requirement already satisfied: six>=1.9 in c:\users\shrad\anaconda3\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\shrad\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\shrad\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

file_path = "APM-Report-16896.xls"

# Read all tables from the HTML report
tables = pd.read_html(file_path, flavor="lxml")

print(len(tables))  # see how many tables
first_sheet = tables[0]  # usually first table is what you want

first_sheet.head()

1

  ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan  \
                                                                                                                                                                                                                                                  Facility
0                                                ATL
1                                                ATL
2                                                BOS
3                                                BOS
4                                                BWI

                                                                        \
  Calendar Year Scheduled Departures Departures For Metric Computation
0          2024               383767                            393998
1          2025               391746                            399706
2          2024               188962                            205083
3          2025               192097                            205866
4          2024               104638                            115181

                                                     \
  Delayed Gate Departures % Delayed Gate Departures
0                   65163                     16.54
1                   72795                     18.21
2                   35307                     17.22
3                   36835                     17.89
4                   27786                     24.12

                                                                          \
  Average Minutes Of Delay Per Delayed Gate Departure Scheduled Arrivals
0                                              42.26              383090
1                                              44.79              391147
2                                              43.06              188964
3                                              44.81              191670
4                                              38.18              104644

                                                         \
  Arrivals For Metric Computation Delayed Gate Arrivals
0                          393904                 53460
1                          399954                 56083
2                          204874                 34898
3                          205314                 39155
4                          115122                 19563

                                                        Unnamed: 11_level_0
  % Delayed Gate Arrivals Average Minutes Of Delay Per Delayed Gate Arrival
0                   13.57                                             52.23
1                   14.02                                             55.48
2                   17.03                                             49.62
3                   19.07                                             51.06
4                   16.99                                             43.60

In [5]:
print(first_sheet.columns)
print(first_sheet.head(10))

MultiIndex([('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            ('ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan', ...),
            (                                                                                                                                                                                                                                     'Unnamed: 11_level_0', ...)],
           )
  ASPM : Airport Analysis : Delayed Flights ReportFrom 01/2024 To 12/2025 ; Airport=ATL, BOS, BWI, CLT, DCA, DEN, DFW, DTW, EWR, FLL, HNL, IAD, IAH, JFK, LAS, LAX, LGA, MCO, MDW, MEM, MIA, MSP, ORD, PHL, PHX, SAN, SEA, SFO, SLC, TPA : Use Flight Plan  \
                                                                                                                                                                                                                                                  Facility
0                                                ATL
1                                                ATL
2                                                BOS
3                                                BOS
4                                                BWI
5                                                BWI
6                                                CLT
7                                                CLT
8                                                DCA
9                                                DCA

                                                                        \
  Calendar Year Scheduled Departures Departures For Metric Computation
0          2024               383767                            393998
1          2025               391746                            399706
2          2024               188962                            205083
3          2025               192097                            205866
4          2024               104638                            115181
5          2025               101145                            112968
6          2024               272229                            281945
7          2025               262962                            272043
8          2024               147528                            147287
9          2025               151247                            147506

                                                     \
  Delayed Gate Departures % Delayed Gate Departures
0                   65163                     16.54
1                   72795                     18.21
2                   35307                     17.22
3                   36835                     17.89
4                   27786                     24.12
5                   24125                     21.36
6                   55467                     19.67
7                   47518                     17.47
8                   20470                     13.90
9                   26092                     17.69

                                                                          \
  Average Minutes Of Delay Per Delayed Gate Departure Scheduled Arrivals
0                                              42.26              383090
1                                              44.79              391147
2                                              43.06              188964
3                                              44.81              191670
4                                              38.18              104644
5                                              42.89              101152
6                                              45.05              272290
7                                              45.55              262960
8                                              43.39              147393
9                                              46.83              151255

                                                         \
  Arrivals For Metric Computation Delayed Gate Arrivals
0                          393904                 53460
1                          399954                 56083
2                          204874                 34898
3                          205314                 39155
4                          115122                 19563
5                          113045                 20043
6                          281915                 43818
7                          272043                 36132
8                          147473                 22663
9                          147972                 29975

                                                        Unnamed: 11_level_0
  % Delayed Gate Arrivals Average Minutes Of Delay Per Delayed Gate Arrival
0                   13.57                                             52.23
1                   14.02                                             55.48
2                   17.03                                             49.62
3                   19.07                                             51.06
4                   16.99                                             43.60
5                   17.73                                             47.24
6                   15.54                                             48.62
7                   13.28                                             51.90
8                   15.37                                             49.60
9                   20.26                                             54.73

In [6]:
df = first_sheet.copy()

# Flatten multiindex
df.columns = [col[-1] if isinstance(col, tuple) else col for col in df.columns]

In [7]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
df

,facility,calendar_year,scheduled_departures,departures_for_metric_computation,delayed_gate_departures,%_delayed_gate_departures,average_minutes_of_delay_per_delayed_gate_departure,scheduled_arrivals,arrivals_for_metric_computation,delayed_gate_arrivals,%_delayed_gate_arrivals,average_minutes_of_delay_per_delayed_gate_arrival
0,ATL,2024,383767,393998,65163,16.54,42.26,383090,393904,53460,13.57,52.23
1,ATL,2025,391746,399706,72795,18.21,44.79,391147,399954,56083,14.02,55.48
2,BOS,2024,188962,205083,35307,17.22,43.06,188964,204874,34898,17.03,49.62
3,BOS,2025,192097,205866,36835,17.89,44.81,191670,205314,39155,19.07,51.06
4,BWI,2024,104638,115181,27786,24.12,38.18,104644,115122,19563,16.99,43.60
...,...,...,...,...,...,...,...,...,...,...,...,...
56,SLC,2024,118187,135152,20669,15.29,42.46,118212,135047,20640,15.28,45.15
57,SLC,2025,121936,139130,19240,13.83,43.42,121936,139058,20259,14.57,46.12
58,TPA,2024,91137,100537,13999,13.92,43.21,91174,100738,21384,21.23,49.00
59,TPA,2025,91477,102798,14191,13.80,43.35,91480,102805,21968,21.37,48.75
60,Total :,Total :,11257343,12151631,2209217,18.18,43.61,11238608,12144159,2102915,17.32,52.61

In [8]:
df = df.rename(columns={
    'facility': 'airport',
    'calendar_year': 'year',
    'delayed_gate_arrivals': 'delayed_arrivals',
    'arrivals_for_metric_computation': 'arrivals',
    '%_delayed_gate_arrivals': 'delay_rate',
    'average_minutes_of_delay_per_delayed_gate_arrival': 'avg_delay'
})
df

,airport,year,scheduled_departures,departures_for_metric_computation,delayed_gate_departures,%_delayed_gate_departures,average_minutes_of_delay_per_delayed_gate_departure,scheduled_arrivals,arrivals,delayed_arrivals,delay_rate,avg_delay
0,ATL,2024,383767,393998,65163,16.54,42.26,383090,393904,53460,13.57,52.23
1,ATL,2025,391746,399706,72795,18.21,44.79,391147,399954,56083,14.02,55.48
2,BOS,2024,188962,205083,35307,17.22,43.06,188964,204874,34898,17.03,49.62
3,BOS,2025,192097,205866,36835,17.89,44.81,191670,205314,39155,19.07,51.06
4,BWI,2024,104638,115181,27786,24.12,38.18,104644,115122,19563,16.99,43.60
...,...,...,...,...,...,...,...,...,...,...,...,...
56,SLC,2024,118187,135152,20669,15.29,42.46,118212,135047,20640,15.28,45.15
57,SLC,2025,121936,139130,19240,13.83,43.42,121936,139058,20259,14.57,46.12
58,TPA,2024,91137,100537,13999,13.92,43.21,91174,100738,21384,21.23,49.00
59,TPA,2025,91477,102798,14191,13.80,43.35,91480,102805,21968,21.37,48.75
60,Total :,Total :,11257343,12151631,2209217,18.18,43.61,11238608,12144159,2102915,17.32,52.61

In [9]:
# keeping only useful columns
df = df[[
    'airport',
    'year',
    'arrivals',
    'delayed_arrivals',
    'delay_rate',
    'avg_delay'
]]
df

    airport     year  arrivals  delayed_arrivals  delay_rate  avg_delay
0       ATL     2024    393904             53460       13.57      52.23
1       ATL     2025    399954             56083       14.02      55.48
2       BOS     2024    204874             34898       17.03      49.62
3       BOS     2025    205314             39155       19.07      51.06
4       BWI     2024    115122             19563       16.99      43.60
..      ...      ...       ...               ...         ...        ...
56      SLC     2024    135047             20640       15.28      45.15
57      SLC     2025    139058             20259       14.57      46.12
58      TPA     2024    100738             21384       21.23      49.00
59      TPA     2025    102805             21968       21.37      48.75
60  Total :  Total :  12144159           2102915       17.32      52.61

[61 rows x 6 columns]

In [10]:
# fixing data types
df['year'] = pd.to_numeric(df['year'], errors='coerce')

for col in ['arrivals', 'delayed_arrivals', 'delay_rate', 'avg_delay']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df

C:\Users\shrad\AppData\Local\Temp\ipykernel_79016\3178578376.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = pd.to_numeric(df['year'], errors='coerce')
C:\Users\shrad\AppData\Local\Temp\ipykernel_79016\3178578376.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')

    airport    year  arrivals  delayed_arrivals  delay_rate  avg_delay
0       ATL  2024.0    393904             53460       13.57      52.23
1       ATL  2025.0    399954             56083       14.02      55.48
2       BOS  2024.0    204874             34898       17.03      49.62
3       BOS  2025.0    205314             39155       19.07      51.06
4       BWI  2024.0    115122             19563       16.99      43.60
..      ...     ...       ...               ...         ...        ...
56      SLC  2024.0    135047             20640       15.28      45.15
57      SLC  2025.0    139058             20259       14.57      46.12
58      TPA  2024.0    100738             21384       21.23      49.00
59      TPA  2025.0    102805             21968       21.37      48.75
60  Total :     NaN  12144159           2102915       17.32      52.61

[61 rows x 6 columns]

In [11]:
df['delay_rate_calc'] = df['delayed_arrivals'] / df['arrivals']

C:\Users\shrad\AppData\Local\Temp\ipykernel_79016\4073785805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['delay_rate_calc'] = df['delayed_arrivals'] / df['arrivals']

In [12]:
airport_features = df.groupby('airport').agg({
    'delay_rate': 'mean',
    'avg_delay': 'mean'
}).rename(columns={
    'delay_rate': 'avg_delay_rate',
    'avg_delay': 'avg_delay_minutes'
}).reset_index()
# Convert percentage to decimal
airport_features['avg_delay_rate'] = airport_features['avg_delay_rate'] / 100

In [13]:
volatility = df.groupby('airport')['delay_rate'].std().reset_index()
volatility = volatility.rename(columns={'delay_rate': 'delay_volatility'})

airport_features = airport_features.merge(volatility, on='airport')

In [14]:
airport_features['gdp_proxy_score'] = airport_features['avg_delay_rate']
airport_features.head()

,airport,avg_delay_rate,avg_delay_minutes,delay_volatility,gdp_proxy_score
0,ATL,0.13795,53.855,0.318198,0.13795
1,BOS,0.18050,50.340,1.442498,0.18050
2,BWI,0.17360,45.420,0.523259,0.17360
3,CLT,0.14410,50.260,1.598061,0.14410
4,DCA,0.17815,52.165,3.457752,0.17815

In [15]:
output_csv = 'airport_features.csv'
airport_features.to_csv(output_csv, index=False)
print(f"Exported {len(airport_features)} rows to {output_csv}")

Exported 31 rows to airport_features.csv